// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;

// No seu projeto a key válida é VITE_SUPABASE_PUBLISHABLE_KEY.
// Mantemos fallback para VITE_SUPABASE_ANON_KEY só pra não quebrar caso exista em algum env.
const SUPABASE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY) as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export let supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export function resetSupabaseClient() {
  // NÃO chame supabase.auth.getSession() aqui.
  // getSession pode entrar em lock durante MFA (challenge/verify) e travar a aba.
  // A checagem de auth deve ser feita via getUser() nos gates/ProtectedRoute.

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.error("resetSupabaseClient: env inválido", {
      hasUrl: !!SUPABASE_URL,
      hasKey: !!SUPABASE_KEY,
    });
    return supabase;
  }

  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return supabase;
}
