// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;

// IMPORTANTE: este projeto usa VITE_SUPABASE_PUBLISHABLE_KEY (não ANON_KEY)
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Export "let" para permitir reset, mas SEM trocar key/opções.
export let supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Mantemos a função (porque está importada em alguns lugares),
// mas ela precisa recriar com EXATAMENTE as mesmas opções do client acima.
export function resetSupabaseClient() {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return supabase;
}
